#include "venturian_areas.dm"
#include "venturian_jobs.dm"
#include "venturian_radio.dm"
#include "venturian_stuff.dm"
#include "venturian_shuttle.dm"

/datum/map_template/ruin/away_site/venturian
	name =  "Venturian"
	id = "awaysite_venturian"
	description = "Contracted Engineers on FTEV Venturian"
	suffixes = list("venturian/venturian.dmm")
	spawn_cost = 0.2
	player_cost = 0
	accessibility_weight = 10
	spawn_weight = 0
	shuttles_to_initialise = list(/datum/shuttle/autodock/overmap/venturian)
	area_usage_test_exempted_root_areas = list(/area/venture)

/obj/submap_landmark/joinable_submap/venturian
	name =  "Venturian Shuttle"
	archetype = /singleton/submap_archetype/venturian

#define WEBHOOK_SUBMAP_LOADED_VENTURIAN "webhook_submap_venturian"

/singleton/webhook/submap_loaded/venturian
	id = WEBHOOK_SUBMAP_LOADED_VENTURIAN

/singleton/submap_archetype/venturian
	descriptor = "Contracted Engineering Shuttle"
	map = "Venturian Shuttle"
	crew_jobs = list(/datum/job/submap/venturian)
	call_webhook = WEBHOOK_SUBMAP_LOADED_VENTURIAN

#undef WEBHOOK_SUBMAP_LOADED_VENTURIAN

/obj/overmap/visitable/sector/venturerock
	name = "asteroid field"
	desc = "A recent collision of two iron-nickel asteroids, surrounded by a dense debris field. The high metal content and debris generated by the impact is causing errant sensor returns. No landing sites detected."
	icon_state = "asteroid"
	hide_from_reports = TRUE
	sensor_visibility = 10
	icon_state = "meteor4"
	initial_restricted_waypoints = list(
		"FTEV Venturian" = list("nav_venturian_shuttle")
	)

/obj/submap_landmark/spawnpoint/venturian
	name = "Contract Engineer"
	movable_flags = MOVABLE_FLAG_EFFECTMOVE
